[package]
name = "brightnessctl"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27"
egui = "0.27"
windows = { version = "0.56", features = [
  "Win32_Graphics_Dxgi",
  "Win32_Graphics_Gdi",
  "Win32_UI_WindowsAndMessaging",
  "Win32_Devices_Display",
  "Win32_System_Com"
]}

[profile.release]
lto = true
panic = "abort"
strip = true
codegen-units = 1
